; Da Vinci default config

(add-key-binding \w :ctrl quit-editor)
(add-key-binding :up move-cursor-up)
(add-key-binding :right move-cursor-right)
(add-key-binding :left move-cursor-left)
(add-key-binding :down move-cursor-down)
(add-key-binding :page-up page-up)
(add-key-binding :page-down page-down)
(add-key-binding :home move-cursor-to-beginning-of-line)
(add-key-binding :end move-cursor-to-end-of-line)
(add-key-binding :backspace delete-previous-character)
(add-key-binding :enter insert-newline-at-cursor)
(add-key-binding :tab (insert-string-at-cursor "  "))
(add-key-binding \x :ctrl (set-key-modifier :command-mode))
(add-key-binding \x :command-mode (unset-key-modifier :command-mode))
(add-key-binding \s :command-mode format-and-save)
(add-key-binding \k :command-mode delete-line)
(add-key-binding \l :command-mode delete-until-end-of-line)
(add-key-binding \j :command-mode delete-from-beginning-of-line)
(add-key-binding \d :command-mode duplicate-line)
(set-character-handler insert-character-at-cursor)
